name: Solidity Smart Contracts (Compile, Tests)

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 14
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - name: Go to Soldity repository and install dependencies
        run: cd solidity/ && npm ci
      - name: Compile contracts
        run: npm run compile
      - name: Test contracts
        run: npm run test